devtools:
  livereload:
    enabled: true

spring:
  output.ansi.enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sotong?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: root1234

#     docker
    url: jdbc:mysql://mysql:3306/sotong?serverTimezone=UTC&characterEncoding=UTF-8
    username: sotong
    password: sotong


  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    com:
      example: info
    org:
      hibernate:
        SQL: DEBUG

app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorld

# logging.level.com.example: info
